name = "rtm-mcp-server"
main = "src/index.ts"
compatibility_date = "2025-03-10"
compatibility_flags = ["nodejs_compat"]

# Production configuration is now the default
[vars]
SERVER_URL = "https://rtm-mcp-server-production.vcto-6e7.workers.dev"

[[kv_namespaces]]
binding = "AUTH_STORE"
id = "7ca3e0b80b9e429488a0be33d7e259fb"

[[durable_objects.bindings]]
name = "MCP_OBJECT"
class_name = "RtmMCP"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["RtmMCP"]

[[kv_namespaces]]
binding = "OAUTH_DATABASE"
id = "d863eecd0c5c45f89e0406dbd4d71f87"

[[kv_namespaces]]
binding = "OAUTH_SESSIONS"
id = "ce0578d4c9184ebaa675932efa919c8f"