name = "rtm-mcp-server"
main = "src/index.ts"
compatibility_date = "2025-03-10"
compatibility_flags = ["nodejs_compat"]

[env.production]
vars = { SERVER_URL = "https://rtm-mcp-server.YOUR-ACCOUNT.workers.dev" }

[vars]
# Add these via wrangler secret put
# RTM_API_KEY = "your-api-key"
# RTM_SHARED_SECRET = "your-shared-secret"
SERVER_URL = "http://localhost:8787"

[[kv_namespaces]]
binding = "AUTH_STORE"
id = "YOUR-KV-NAMESPACE-ID"
preview_id = "YOUR-KV-NAMESPACE-ID"

[[durable_objects]]
bindings = [
  { name = "MCP_OBJECT", class_name = "RtmMCP" }
]

[observability]
enabled = true