name = "project-cowflare"
main = "src/index.ts"
compatibility_date = "2025-01-15"

# Account ID will be set during deployment
# account_id = "your-account-id"

# KV namespace for OAuth token storage
[[kv_namespaces]]
binding = "AUTH_STORE"
id = "mock-auth-store"
preview_id = "mock-auth-store-preview"

# Durable Objects for MCP session state
[[durable_objects.bindings]]
name = "MCP_SESSIONS"
class_name = "CowflareMCP"
script_name = "project-cowflare"

# Environment variables for local development
[vars]
MOCK_CLIENT_ID = "mock-client-local"
MOCK_CLIENT_SECRET = "mock-secret-local"

# Future RTM configuration (commented out for now)
# RTM_CLIENT_ID = "your-rtm-client-id"
# RTM_CLIENT_SECRET = "your-rtm-client-secret"
# RTM_ENDPOINT = "https://rtm.cloudflare.com"

# Development settings
[dev]
port = 8787
local_protocol = "http"

# Build configuration
[build]
command = "npm install && npm run build"

[build.upload]
format = "modules"
main = "./src/index.ts"

# TypeScript support
[typescript]
enabled = true